apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mlops-assignment-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mlops-assignment-service
  minReplicas: 1        # Start with 1 pod by default
  maxReplicas: 3        # Scale up to 3 pods max
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Target 60% CPU per pod
