apiVersion: v1
kind: Service
metadata:
  name: mlops-assignment-service
spec:
  selector:
    app: mlops-assignment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
